// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteReviews.Data;

#nullable disable

namespace SiteReviews.Migrations
{
    [DbContext(typeof(SiteReviewsContext))]
    partial class SiteReviewsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SiteReviews.Models.Fotografias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Fotografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObjetosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjetosId");

                    b.ToTable("Fotografias");
                });

            modelBuilder.Entity("SiteReviews.Models.Objetos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Capa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plataforma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Objetos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Objetos");
                });

            modelBuilder.Entity("SiteReviews.Models.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriadorFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FilmesId")
                        .HasColumnType("int");

                    b.Property<int?>("JogosId")
                        .HasColumnType("int");

                    b.Property<int>("ObjetoFK")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriadorFK");

                    b.HasIndex("FilmesId");

                    b.HasIndex("JogosId");

                    b.HasIndex("ObjetoFK");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Conteudo = "When you finish the show you'll never be the same..I guarantee you",
                            CriadorFK = 1,
                            DataCriacao = new DateTime(2022, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ObjetoFK = 1,
                            Rating = 10
                        });
                });

            modelBuilder.Entity("SiteReviews.Models.Utilizadores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Fotografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUtilizador")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("admin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNascimento = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "josesilva5@gmail.com",
                            Fotografia = "Jose.png",
                            NomeUtilizador = "josesilva",
                            admin = false
                        },
                        new
                        {
                            Id = 2,
                            DataNascimento = new DateTime(2004, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariasantos1@gmail.com",
                            Fotografia = "Maria.jpg",
                            NomeUtilizador = "mariasantos",
                            admin = false
                        },
                        new
                        {
                            Id = 3,
                            DataNascimento = new DateTime(2007, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ricardosousa8@gmail.com",
                            Fotografia = "Ricardo.jpg",
                            NomeUtilizador = "ricardosousa",
                            admin = false
                        });
                });

            modelBuilder.Entity("SiteReviews.Models.Filmes", b =>
                {
                    b.HasBaseType("SiteReviews.Models.Objetos");

                    b.Property<string>("Atores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diretor")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Filmes");
                });

            modelBuilder.Entity("SiteReviews.Models.Jogos", b =>
                {
                    b.HasBaseType("SiteReviews.Models.Objetos");

                    b.Property<string>("Desenvolvedores")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Jogos");
                });

            modelBuilder.Entity("SiteReviews.Models.Series", b =>
                {
                    b.HasBaseType("SiteReviews.Models.Objetos");

                    b.Property<string>("Atores")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Series_Atores");

                    b.Property<string>("Diretor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Series_Diretor");

                    b.Property<int>("NEpisodios")
                        .HasColumnType("int");

                    b.Property<int>("NTemporadas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Series");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capa = "breakingbad.jpg",
                            DataLancamento = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
                            Nome = "Breaking Bad",
                            Plataforma = "Netflix",
                            NEpisodios = 0,
                            NTemporadas = 0
                        });
                });

            modelBuilder.Entity("SiteReviews.Models.Fotografias", b =>
                {
                    b.HasOne("SiteReviews.Models.Objetos", null)
                        .WithMany("ListaFotografias")
                        .HasForeignKey("ObjetosId");
                });

            modelBuilder.Entity("SiteReviews.Models.Reviews", b =>
                {
                    b.HasOne("SiteReviews.Models.Utilizadores", "Utilizador")
                        .WithMany("ListaReviews")
                        .HasForeignKey("CriadorFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteReviews.Models.Filmes", null)
                        .WithMany("ListaReviews")
                        .HasForeignKey("FilmesId");

                    b.HasOne("SiteReviews.Models.Jogos", null)
                        .WithMany("ListaReviews")
                        .HasForeignKey("JogosId");

                    b.HasOne("SiteReviews.Models.Series", "Objeto")
                        .WithMany("ListaReviews")
                        .HasForeignKey("ObjetoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objeto");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("SiteReviews.Models.Objetos", b =>
                {
                    b.Navigation("ListaFotografias");
                });

            modelBuilder.Entity("SiteReviews.Models.Utilizadores", b =>
                {
                    b.Navigation("ListaReviews");
                });

            modelBuilder.Entity("SiteReviews.Models.Filmes", b =>
                {
                    b.Navigation("ListaReviews");
                });

            modelBuilder.Entity("SiteReviews.Models.Jogos", b =>
                {
                    b.Navigation("ListaReviews");
                });

            modelBuilder.Entity("SiteReviews.Models.Series", b =>
                {
                    b.Navigation("ListaReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
