// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteReviews.Data;

#nullable disable

namespace SiteReviews.Migrations
{
    [DbContext(typeof(SiteReviewsContext))]
    partial class SiteReviewsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SiteReviews.Models.Fotografias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Fotografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorFK");

                    b.ToTable("Fotografias");
                });

            modelBuilder.Entity("SiteReviews.Models.Objetos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fotografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plataforma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Objetos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Objetos");
                });

            modelBuilder.Entity("SiteReviews.Models.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Conteudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriadorFK")
                        .HasColumnType("int");

                    b.Property<int?>("FilmesId")
                        .HasColumnType("int");

                    b.Property<int>("IdObjetoFK")
                        .HasColumnType("int");

                    b.Property<int?>("JogosId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriadorFK");

                    b.HasIndex("FilmesId");

                    b.HasIndex("IdObjetoFK");

                    b.HasIndex("JogosId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SiteReviews.Models.Utilizadores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUtilizador")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("SiteReviews.Models.Filmes", b =>
                {
                    b.HasBaseType("SiteReviews.Models.Objetos");

                    b.Property<string>("Atores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diretor")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Filmes");
                });

            modelBuilder.Entity("SiteReviews.Models.Jogos", b =>
                {
                    b.HasBaseType("SiteReviews.Models.Objetos");

                    b.Property<string>("Desenvolvedores")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Jogos");
                });

            modelBuilder.Entity("SiteReviews.Models.Series", b =>
                {
                    b.HasBaseType("SiteReviews.Models.Objetos");

                    b.Property<string>("Atores")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Series_Atores");

                    b.Property<string>("Diretor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Series_Diretor");

                    b.Property<int>("NEpisodios")
                        .HasColumnType("int");

                    b.Property<int>("NTemporadas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Series");
                });

            modelBuilder.Entity("SiteReviews.Models.Fotografias", b =>
                {
                    b.HasOne("SiteReviews.Models.Utilizadores", "IdUtilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdUtilizador");
                });

            modelBuilder.Entity("SiteReviews.Models.Reviews", b =>
                {
                    b.HasOne("SiteReviews.Models.Utilizadores", "IdUtilizador")
                        .WithMany()
                        .HasForeignKey("CriadorFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteReviews.Models.Filmes", null)
                        .WithMany("ListaReviews")
                        .HasForeignKey("FilmesId");

                    b.HasOne("SiteReviews.Models.Series", "IdObjeto")
                        .WithMany("ListaReviews")
                        .HasForeignKey("IdObjetoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteReviews.Models.Jogos", null)
                        .WithMany("ListaReviews")
                        .HasForeignKey("JogosId");

                    b.Navigation("IdObjeto");

                    b.Navigation("IdUtilizador");
                });

            modelBuilder.Entity("SiteReviews.Models.Filmes", b =>
                {
                    b.Navigation("ListaReviews");
                });

            modelBuilder.Entity("SiteReviews.Models.Jogos", b =>
                {
                    b.Navigation("ListaReviews");
                });

            modelBuilder.Entity("SiteReviews.Models.Series", b =>
                {
                    b.Navigation("ListaReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
